version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: heidi-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: register
    ports:
      - "3307:3307"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: ..
    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=register
    env_file:
      - .env

volumes:
  mysql_data:
